{{- range $name, $item := $.Values.externalServices }}

apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: {{ $item.mesh }}
metadata:
  name: {{ $item.name }}
spec:
  tags:
    kuma.io/service: {{ $item.name }}
    kuma.io/protocol: {{ $item.protocol }} # optional, one of http, http2, tcp, grpc, kafka
  networking:
    address: {{ $item.address }}

{{- end }}