{{- range $name, $item := $.Values.meshes }}
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata: 
  name: {{ $item.name }}
  {{- with $item.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: 
  {{- if $item.networking }}
  networking:
    outbound:
      passthrough: {{ $item.networking.outbound.passthrough }}
  {{- end }}
  {{- if $item.mtls }}
  mtls: 
    enabledBackend: {{ $item.mtls.enabledBackend }}
    {{- with $item.mtls.backends }}
    backends:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if $item.tracing }}
  tracing: 
    defaultBackend: {{ $item.tracing.defaultBackend }}
    {{- with $item.tracing.backends }}
    backends:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if $item.logging }}
  logging: 
    defaultBackend: {{ $item.logging.defaultBackend }}
    {{- with $item.logging.backends }}
    backends:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if $item.metrics }}
  metrics: 
    enabledBackend: {{ $item.metrics.enabledBackend }}
    {{- with $item.metrics.backends }}
    backends:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
---
{{- end }}