# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# wazuh-indexer StatefulSet: 3 master nodes.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
spec:
  replicas: {{ .Values.indexer.replicas }}
  selector:
    matchLabels:
      app: wazuh-indexer
  serviceName: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
      name: wazuh-indexer
    spec:
      # Set the wazuh-indexer volume permissions so the wazuh-indexer user can use it
      volumes:
        - name: indexer-cert
          secret:
            secretName: indexer-cert
        - name: indexer-conf
          configMap:
            name: indexer-conf
        - name: wazuh-indexer
          emptyDir:
            sizeLimit: 50Gi
      initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /var/lib/wazuh-indexer'
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
        - name: increase-the-pod-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.8.1
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: '-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true'
            - name: CLUSTER_NAME
              value: calcguard
            - name: NETWORK_HOST
              value: "0.0.0.0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: wazuh-indexer
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: 'true'
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
            - name: indexer-cert
              mountPath: /usr/share/wazuh-indexer/certs/node-key.pem
              subPath: tls.key
              readOnly: true
            - name: indexer-cert
              mountPath: /usr/share/wazuh-indexer/certs/node.pem
              subPath: tls.crt
              readOnly: true
            - name: indexer-cert
              mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem
              subPath: ca.crt
              readOnly: true
            - name: indexer-cert
              mountPath: /usr/share/wazuh-indexer/certs/admin.pem
              subPath: tls.crt
              readOnly: true
            - name: indexer-cert
              mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem
              subPath: tls.key
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch.yml
              subPath: opensearch.yaml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
              subPath: users.yaml
              readOnly: true
          ports:
            - containerPort: 9200
              name: indexer-rest
            - containerPort: 9300
              name: indexer-nodes
  # volumeClaimTemplates:
  #   - metadata:
  #       name: wazuh-indexer
  #       namespace: wazuh-indexer-cluster
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       storageClassName: wazuh-storage
  #       resources:
  #         requests:
  #           storage: 500Mi