{{- range $name, $cert := $.Values.certificates }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
spec:
  secretName: {{ $name }}-cert-secret
  commonName: {{ $name }}-cert-secret
  isCA: true
  issuerRef:
    name: {{ $cert.issuer.name }}
    kind: {{ $cert.issuer.kind }}

{{- end }}