apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-job
data:
  {{- range $k, $v := .Values.config }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.openTelemetry.inject }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}-job-files
data:
  {{- range $k, $v := .Values.files }}
  {{- if $v }}
  {{ $k }}: |
    {{- $v  | nindent 4 }} 
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}-job-binary-files
binaryData:
  {{- range $k, $v := .Values.binaryFiles }}
  {{- if $v }}
  {{ $k }}: |
    {{- $v  | nindent 4 }} 
  {{- end }}
  {{- end }}