{{- $fullName := include "app.fullname" . -}}
{{- range $name, $ingress := $.Values.ingress }}
{{- if $ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $name }}
  namespace: {{ $ingress.namespace | default $.Release.Namespace | quote }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .ingressClassName }}
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ $fullName }}-{{ $name }}
  {{- end }}
{{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ .serviceName | default $fullName | quote }}
                port:
                  number: {{ .servicePort | default $.Values.service.ports.app.port }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
