{{- range $item := $.Values.persistence }}

{{- if $item.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  {{ include "app.fullname" . }}-{{ $item.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if $item.storageClass }}
  storageClassName: {{ $item.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ $item.accessMode | quote }}
  resources:
    requests:
      storage: {{ $item.size | quote }}

{{- end }}
{{- end }}