apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
  {{- if $v }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}-files
type: Opaque
data:
  {{- range $k, $v := .Values.secretFiles }}
  {{- if $v }}
  {{ $k }}: |
    {{- $v  | b64enc | nindent 4 }} 
  {{- end }}
  {{- end }}
{{- range $name, $item := $.Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}-{{ $name }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $item }}
{{- end }}
{{- if $.Values.keys.generate.ecdsa  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}-ecdsa-generated
type: Opaque
data:
  private: {{ genPrivateKey "ecdsa" | b64enc }}
{{- end }}
{{- with $.Values.keys.static.ecdsa  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}-ecdsa-static
type: Opaque
data:
  private: {{ . | b64enc }}
{{- end }}