apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
  {{- if $v }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}